name: General
main: net.craftstars.general.General
authors:
  - Celtic Minstrel
  - Plutonium239
version: 4.1
softdepend:
  - BOSEconomy
  - iConomy
  - Help
  - BookWorm
commands:
  general:
    #permission: general.admin
    description: Administrates the plugin.
    aliases: [help, motd]
    usage: /general reload|die|motd|help
  chat.tell:
    #permission: general.tell
    description: Sends another player a private message.
    usage: /<command> <player> <message>
  chat.away:
    #permission: general.away
    description: Sets your away message
    usage: /<command> [message]
  info.iteminfo:
    #permission: general.iteminfo
    description: Shows info about the item you're holding
    usage: /<command> [slot] [player]
  info.playerlist:
    description: Displays all players that are online.
    #permission: general.playerlist
    usage: /<command> [world]
  info.who:
    #permission: general.who
    description: Displays information about a player.
    aliases: [whoami]
    usage: /<command> [player]
  info.getpos:
    #permission: general.getpos
    description: Displays detailed information about your position.
    usage: /<command> [<player>] [compass|dir|pos|rot]
  info.worldinfo:
    #permission: general.worldinfo
    description: Gives info on a world
    usage: /<command> [<world>]
  inven.give:
    #permission: general.give
    description: Users to give yourself or another player an item.
    usage: /<command> item[:data] [amount] [player]
  inven.items:
    #permission: general.give.mass
    description: Gives several items all at once
    usage: /<command> <item1> <item2> ...etc
  inven.kit:
    #permission: general.kit
    description: Gives you a kit.
    usage: /kit [kit-name]
  inven.clear:
    #permission: general.clear
    description: Clears your inventory.
    usage: /<command> [player] [pack|armo[u]r|quickbar|all]
  inven.take:
    #permission: general.take
    description: Removes something from your inventory.
    usage: /<command> item[:data] [amount] [player]
  inven.masstake:
    #permission: general.take.mass
    description: Removes multiple things from your inventory.
    usage: /<command> item1 item2 ... itemn [player]
  inven.mode:
    #permission: general.gamemode
    description: Sets the game mode of a player
    usage: /<command> [player] mode
  teleport.setspawn:
    #permission: general.spawn.set
    description: Sets to the spawn location of your current world (or the specified one).
    usage: /<command> [<dest>]
  teleport.go:
    #permission: general.teleport
    description: Teleports a/multiple/all player(s) to another players location.
    usage: /<command> [<who>] <dest>
  misc.time:
    #permission: general.time
    description: Displays or modifies current world time.
    usage: |
           /<command> [<world>] [=|+|-]<time|duration>
           /<command> add|set <time|duration>
  misc.weather:
    #permission: general.weather
    description: Affects the weather
    usage: /<command> [<world>] <weather>
  misc.heal:
    #permission: general.heal
    description: Restores your health. (Can also reduce it if you give a negative amount.)
    aliases: [hurt]
    usage: /<command> [player] [amount]
  misc.mobspawn:
    #permission: general.mobspawn
    description: Spawns a mob.
    usage: /<command> <mob-name>[;<mount>] [<how-many>]
  admin.op:
    #permission: general.op
    description: Promotes a player to operator
    usage: /<command> [player1 player2 ... playerN]
  admin.deop:
    #permission: general.deop
    description: Demotes a player from operator
    usage: /<command> [player1 player2 ... playerN]
  admin.ban:
    #permission: general.ban
    description: Bans a player from the server
    usage: /<command> player1 player2 ... playerN
  admin.pardon:
    #permission: general.pardon
    description: Pardons a banned player so they can connect again
    usage: /<command> player1 player2 ... playerN
  admin.kick:
    #permission: general.kick
    description: Kicks a player off the server
    usage: /<command> player [reason]
  admin.shutdown:
    #permission: general.stop
    description: Kicks off all players and shuts down the server.
    usage: /<command> [delay] [reason]
permissions:
  # Wildcard syntax for backwards compatibility
  general.*: {children: {general.unlimited: true}}
  general.teleport.*: {children: {general.teleport.all: true}}
  general.setspawn.*: {children: {general.setspawn: true}}
  general.mobspawn.*: {children: {general.mobspawn: true}}
  general.kit.*: {children: {general.kit: true}}
  general.kit.*.instant: {children: {general.kit-now: true}}
  general.mobspawn.*: {children: {general.mobspawn: true}}
  general.give.*: {children: {general.give.unlimited: true}}
  general.give.group.*: {children: {general.give.groups: true}}
  general.give.item.*: {children: {general.give.any: true}}
  general.time.*: {children: {general.time: true}}
  general.who.*: {children: {general.who.ip: true}}
  general.weather.*: {children: {general.weather: true}}
  general.heal.*: {children: {general.heal: true, general.hurt: true}}
  general.getpos.*: {children: {general.getpos.other: true}}
  general.admin.*: {children: {general.config: true}}
  general.clear.*: {children: {general.clear.other: true}}
  general.take.*: {children: {general.take.other: true, general.take.mass: true}}
  general.gamemode.*: {children: {general.gamemode: true}}
  general.gamemode.force.survival:
    description: Forces your gamemode to survival.
    children:
      general.gamemode.set: false
  general.gamemode.force.creative:
    description: Forces your gamemode to creative.
    children:
      general.gamemode.set: false
  # Actual permissions start here
  general.admin:
    description: Gives all General permissions.
    default: op
    children:
      general:
        description: Gives all relatively safe General permissions.
        children:
          general.give.unlimited:
            description: Gives full access to the /give command.
            children:
              general.give:
                description: Gives basic access to the /give command.
              general.give.infinite:
                description: Gives access to /give for infinite stacks.
              general.give.mass:
                description: Gives access to /give for large quantities, and to /items.
              general.give.any:
                description: Gives permission to get any item regardless of whitelisting/blacklisting.
                children:
                  general.give.groups: true # Defined dynamically
                  general.give.groupless: true # Defined dynamically
          general.gamemode:
            description: Gives full access to the /gamemode command.
            children:
              general.gamemode.view:
                description: Lets you view the game mode of other people.
              general.gamemode.set.world:
                description: Lets you set the game mode of everyone in a world.
                children:
                  general.gamemode.set.other:
                    description: Lets you set anyone's game mode.
                    children:
                      general.gamemode.set:
                        description: Lets you set your own game mode.
          general.clear.other:
            description: Lets you clear the inventory of others.
            children:
              general.clear:
                description: Gives basic access to the /clear command.
          general.take.other:
            description: Lets you take from the inventory of others.
            children:
              general.take:
                description: Gives basic access to the /take command.
          general.take.mass:
            description: Gives access to the /masstake command.
          general.kit: true # Defined dynamically
          general.teleport.all:
            description: Gives full access to the teleport command, including bypassing warm-up
            children:
              general.teleport: true # Defined dynamically
              general.teleport.mass:
                description: Allows you to teleport several entities at a time.
          general.setspawn: true # Defined dynamically
          general.mobspawn: true # Defined dynamically
          general.mobspawn.mass:
            description: Allows you to spawn large numbers of mobs all at once.
          general.away:
            description: Allows you to set an away message.
          general.worldinfo:
            description: Allows you to view info about worlds.
          general.playerlist:
            description: Allows you to view who's online.
          general.tell:
            description: Allows you to private message players.
          general.iteminfo.other:
            description: Allows you to see information about the items anyone is carrying.
            children:
              general.iteminfo:
                description: Allows you to see information about the item you're holding.
          general.time:
            description: Allows you to view and set the time.
            children:
              general.time.view:
                description: Allows you to view the time.
              general.time.set:
                description: Allows you to set the time.
          general.who:
            description: Gives basic access to the /who command.
          general.getpos.other:
            description: Allows you to see anyone's position.
            children:
              general.getpos:
                description: Allows you to see your position with /getpos, /where, and /compass.
          general.heal:
            description: Gives access to /heal (and /hurt with negative amounts).
          general.hurt:
            description: Gives access to /hurt (and /heal with negative amounts).
          general.weather:
            description: Allows you to tamper with the weather.
            children:
              general.weather.view:
                description: Allows you to see a weather report.
              general.weather.set:
                description: Allows you to start and stop storms.
              general.weather.thunder:
                description: Allows you to start and stop thunder.
              general.weather.zap:
                description: Allows you to summon lightning.
      general.who.ip:
        description: Allows you to view players' IP addresses in the /who command (if this feature is enabled).
        children:
          general.who: true
      general.config:
        description: Gives access to all administrative commands.
        default: op
        children:
          general.admin.reload:
            description: Allows you to reload the configuration from the files.
          general.admin.item:
            description: Allows you to edit item names and aliases, and whitelist/blacklist items.
          general.admin.save:
            description: Allows you to force General to save its configuration.
          general.admin.kit:
            description: Allows you to edit the kit definitions.
          general.admin.economy:
            description: Allows you to edit costs of various commands.
          general.admin.set:
            description: Allows you to set various configuration variables.
          general.admin.genlang:
            description: Allows you to generate all language format strings in the language file.
      general.op:
        description: Gives permission to grant operator status.
        default: op
      general.deop:
        description: Gives permission to remove operator status.
        default: op
      general.kick:
        description: Gives permission to kick people off the server.
        default: op
      general.ban:
        description: Gives permission to ban people from the server.
        default: op
      general.stop.now
        description: Gives permission to stop the server without a grace delay.
        default: op
        children:
      general.stop:
        description: Gives permission to shut down the server.
      general.pardon:
        description: Gives permission to pardon banned people on the server.
        default: op
      general.bypass:
        description: Gives permissions that involve bypassing normal restrictions, such as delays or economy.
        children:
          general.no-money:
            description: Allows you to use things free of cost that normally require money.
          general.kit-now: true # Defined dynamically
          general.teleport.instant: true # Defined dynamically
          general.time.instant:
            description: Allows you to meddle with the time with no cooldown period.
            children:
              general.time: true
          general.weather.instant:
            description: Allows you to tamper with the weather with no cooldown period.
            children:
              general.weather.view: true
              general.weather.set.instant:
                description: Bypass the cooldown period when starting or stopping storms.
                children:
                  general.weather.set: true
              general.weather.thunder.instant:
                description: Bypass the cooldown period when starting or stopping thunder.
                children:
                  general.weather.thunder: true
              general.weather.zap.instant:
                description: Bypass the cooldown period when summoning lightning.
                children:
                  general.weather.zap: true
  # Some additional shortcuts
  general.basic:
    description: Gives a set of basic, harmless General permissions.
    default: true
    children:
      general.time.view: true
      general.playerlist: true
      general.who: true
      general.away: true
      general.getpos: true
      general.tell: true
  general.mobspawn.neutral.angry:
    description: Allows you to spawn any neutral mob you have access to as already angry.
    children:
      general.mobspawn.wolf.angry: true
      general.mobspawn.pig-zombie.angry: true 
  general.mobspawn.sheep.natural:
    description: Lets you spawn any naturally-occurring colour of sheep.
    children:
      general.mobspawn.sheep.white: true
      general.mobspawn.sheep.silver: true
      general.mobspawn.sheep.gray: true
      general.mobspawn.sheep.black: true
      general.mobspawn.sheep.brown: true
      general.mobspawn.sheep.pink: true
